from load_env import SECRET_KEY, ENCRYPT_ALGORITHM, LIFETIME_CODE, SEND_CODE_INTERVAL

SECRET_KEY = SECRET_KEY
ENCRYPT_ALGORITHM = ENCRYPT_ALGORITHM
LIFETIME_CODE = LIFETIME_CODE
SEND_CODE_INTERVAL = SEND_CODE_INTERVAL
